// Auto-generated by @inaumanmajeed/skeletonify-generate. DO NOT EDIT.

export const skeletonMap: Record<string, () => Promise<{ default: unknown }>> = {
  "DashboardCard/DashboardCard": () => import("./DashboardCard__DashboardCard.skeleton.json"),
  "ProfileCard/ProfileCard": () => import("./ProfileCard__ProfileCard.skeleton.json"),
  "TableRowList/TableRowList": () => import("./TableRowList__TableRowList.skeleton.json"),
};

export const skeletonNames: Record<string, string> = {
  "DashboardCard": "DashboardCard/DashboardCard",
  "ProfileCard": "ProfileCard/ProfileCard",
  "TableRowList": "TableRowList/TableRowList",
};
