import { parse } from "@babel/parser";
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname, basename, extname, relative, resolve } from "path";
import { parseJSXFromBody } from "./jsxParser.js";
import { buildDescriptor, type Descriptor } from "./descriptorBuilder.js";
import type { Statement, FunctionDeclaration, VariableDeclaration, ExportNamedDeclaration, ExportDefaultDeclaration } from "@babel/types";

export interface GeneratedEntry {
  componentName: string;
  key: string;
  descriptor: Descriptor;
  jsonPath: string;
}

function isUpperFirst(name: string): boolean {
  return name.length > 0 && name[0] === name[0].toUpperCase() && name[0] !== name[0].toLowerCase();
}

function extractComponents(body: Statement[]): Array<{ name: string; stmts: Statement[] }> {
  const results: Array<{ name: string; stmts: Statement[] }> = [];

  for (const node of body) {
    // function ProfileCard() { ... }
    if (node.type === "FunctionDeclaration" && node.id && isUpperFirst(node.id.name)) {
      results.push({ name: node.id.name, stmts: node.body.body });
      continue;
    }

    // export function ProfileCard() { ... }
    if (node.type === "ExportNamedDeclaration" && node.declaration?.type === "FunctionDeclaration") {
      const fn = node.declaration;
      if (fn.id && isUpperFirst(fn.id.name)) {
        results.push({ name: fn.id.name, stmts: fn.body.body });
      }
      continue;
    }

    // export default function ProfileCard() { ... }
    if (node.type === "ExportDefaultDeclaration" && node.declaration.type === "FunctionDeclaration") {
      const fn = node.declaration;
      if (fn.id && isUpperFirst(fn.id.name)) {
        results.push({ name: fn.id.name, stmts: fn.body.body });
      }
      continue;
    }

    // const ProfileCard = () => { ... }
    // const ProfileCard = function() { ... }
    if (node.type === "VariableDeclaration" || (node.type === "ExportNamedDeclaration" && node.declaration?.type === "VariableDeclaration")) {
      const decl = node.type === "VariableDeclaration" ? node : (node.declaration as VariableDeclaration);
      for (const d of decl.declarations) {
        if (d.id.type !== "Identifier" || !isUpperFirst(d.id.name) || !d.init) continue;
        const init = d.init;
        if (init.type === "ArrowFunctionExpression" || init.type === "FunctionExpression") {
          const fnBody = init.body;
          if (fnBody.type === "BlockStatement") {
            results.push({ name: d.id.name, stmts: fnBody.body });
          } else if (fnBody.type === "JSXElement" || fnBody.type === "JSXFragment") {
            // Arrow with implicit return: () => <div>...</div>
            const syntheticReturn: Statement = {
              type: "ReturnStatement",
              argument: fnBody,
              start: fnBody.start,
              end: fnBody.end,
              loc: fnBody.loc,
            } as Statement;
            results.push({ name: d.id.name, stmts: [syntheticReturn] });
          }
        }
      }
    }
  }

  return results;
}

function makeKey(filePath: string, baseDir: string, componentName: string): string {
  const rel = relative(baseDir, filePath).replace(/\\/g, "/");
  const withoutExt = rel.replace(/\.(tsx|jsx|ts|js)$/, "");
  return `${withoutExt}/${componentName}`;
}

export function processFile(
  filePath: string,
  baseDir: string
): GeneratedEntry[] {
  const code = readFileSync(filePath, "utf-8");
  const ast = parse(code, {
    sourceType: "module",
    plugins: ["jsx", "typescript"],
    errorRecovery: true,
  });

  const components = extractComponents(ast.program.body);
  const entries: GeneratedEntry[] = [];

  for (const { name, stmts } of components) {
    const ir = parseJSXFromBody(stmts);
    if (!ir) continue;
    const descriptor = buildDescriptor(ir);
    const key = makeKey(filePath, baseDir, name);
    entries.push({ componentName: name, key, descriptor, jsonPath: "" });
  }

  return entries;
}

export function writeDescriptors(
  entries: GeneratedEntry[],
  outDir: string
): void {
  mkdirSync(outDir, { recursive: true });

  for (const entry of entries) {
    const jsonFile = `${entry.key.replace(/\//g, "__")}.skeleton.json`;
    const fullPath = resolve(outDir, jsonFile);
    mkdirSync(dirname(fullPath), { recursive: true });
    writeFileSync(fullPath, JSON.stringify(entry.descriptor, null, 2) + "\n", "utf-8");
    entry.jsonPath = jsonFile;
  }
}

export function writeSkeletonMap(
  entries: GeneratedEntry[],
  outDir: string
): void {
  const lines = [
    "// Auto-generated by @inaumanmajeed/skeletonify-generate. DO NOT EDIT.",
    "",
    "export const skeletonMap: Record<string, () => Promise<{ default: unknown }>> = {",
    ...entries.map(
      (e) => `  "${e.key}": () => import("./${e.jsonPath}"),`
    ),
    "};",
    "",
    "export const skeletonNames: Record<string, string> = {",
    ...entries.map(
      (e) => `  "${e.componentName}": "${e.key}",`
    ),
    "};",
    "",
  ];
  writeFileSync(resolve(outDir, "skeletonMap.ts"), lines.join("\n"), "utf-8");
}
